const data = [
  {
    img: "https://example.com/shoe1.jpg",
    title: "Air Max Running Shoes",
    star: 4.7,
    reviews: 1200,
    prevPrice: 129.99,
    newPrice: 99.99,
    company: "Nike",
    color: "Red",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe2.jpg",
    title: "UltraBoost Sneakers",
    star: 4.8,
    reviews: 950,
    prevPrice: 149.99,
    newPrice: 119.99,
    company: "Adidas",
    color: "Black",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe3.jpg",
    title: "Casual Walking Shoes",
    star: 4.5,
    reviews: 780,
    prevPrice: 79.99,
    newPrice: 59.99,
    company: "Puma",
    color: "White",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe4.jpg",
    title: "Basketball High-Tops",
    star: 4.6,
    reviews: 1100,
    prevPrice: 159.99,
    newPrice: 129.99,
    company: "Jordan",
    color: "Blue",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe5.jpg",
    title: "Classic Leather Sneakers",
    star: 4.4,
    reviews: 870,
    prevPrice: 99.99,
    newPrice: 79.99,
    company: "Reebok",
    color: "Gray",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe6.jpg",
    title: "Trail Running Shoes",
    star: 4.7,
    reviews: 560,
    prevPrice: 119.99,
    newPrice: 99.99,
    company: "Salomon",
    color: "Green",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe7.jpg",
    title: "Lightweight Joggers",
    star: 4.3,
    reviews: 690,
    prevPrice: 69.99,
    newPrice: 49.99,
    company: "Under Armour",
    color: "Black",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe8.jpg",
    title: "Slip-On Loafers",
    star: 4.5,
    reviews: 800,
    prevPrice: 89.99,
    newPrice: 69.99,
    company: "Skechers",
    color: "Brown",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe9.jpg",
    title: "Waterproof Hiking Boots",
    star: 4.8,
    reviews: 420,
    prevPrice: 179.99,
    newPrice: 149.99,
    company: "Columbia",
    color: "Tan",
    category: "Shoes",
  },
  {
    img: "https://example.com/shoe10.jpg",
    title: "Formal Dress Shoes",
    star: 4.6,
    reviews: 900,
    prevPrice: 129.99,
    newPrice: 99.99,
    company: "Clarks",
    color: "Black",
    category: "Shoes",
  },
];

export default data;
